### ISSUE TITLE
Panic when grouping imports

### ISSUE THREAD

**Issue by tie** [mvdan/gofumpt#29]
`gofumpt` panics when grouping unindented standard library and third-party imports.

Tested on the following Go versions:
- `go1.12.6`
- `go1.13-adcb2b1e7a`

Steps to reproduce:

Run `gofumpt` with the following input:

```go
import (
"a"
"a.b"
)
```

Expected output:
```go
import (
	"a"

	"a.b"
)
```

Actual output:
<details>
<summary>stderr</summary>

  ```
  panic: could not set lines to [0 19 23 23 29] [recovered]
  	panic: could not set lines to [0 19 23 23 29]
  
  goroutine 1 [running]:
  golang.org/x/tools/go/ast/astutil.Apply.func1(0xc0000d40c0, 0xc0000bfc50)
  	golang.org/x/tools@v0.0.0-20190625160430-252024b82959/go/ast/astutil/rewrite.go:47 +0xa3
  panic(0x1152ae0, 0xc0000d40f0)
  	runtime/panic.go:663 +0x1b2
  mvdan.cc/gofumpt/internal.(*fumpter).addNewline(0xc0000ce160, 0x2e)
  	mvdan.cc/gofumpt@/internal/gofumpt.go:123 +0x584
  mvdan.cc/gofumpt/internal.(*fumpter).joinStdImports(0xc0000ce160, 0xc0000da080)
  	mvdan.cc/gofumpt@/internal/gofumpt.go:409 +0x1fc
  mvdan.cc/gofumpt/internal.(*fumpter).applyPre(0xc0000ce160, 0xc000082130)
  	mvdan.cc/gofumpt@/internal/gofumpt.go:241 +0x98d
  mvdan.cc/gofumpt/internal.Gofumpt.func1(0xc000082130, 0xc0000d01a0)
  	mvdan.cc/gofumpt@/internal/gofumpt.go:50 +0x39
  golang.org/x/tools/go/ast/astutil.(*application).apply(0xc000082120, 0x11c0a40, 0xc0000de100, 0x119047d, 0x5, 0xc000082168, 0x11c0b80, 0xc0000da080)
  	golang.org/x/tools@v0.0.0-20190625160430-252024b82959/go/ast/astutil/rewrite.go:198 +0x3c18
  golang.org/x/tools/go/ast/astutil.(*application).applyList(0xc000082120, 0x11c0a40, 0xc0000de100, 0x119047d, 0x5)
  	golang.org/x/tools@v0.0.0-20190625160430-252024b82959/go/ast/astutil/rewrite.go:473 +0xa5
  golang.org/x/tools/go/ast/astutil.(*application).apply(0xc000082120, 0x11c1240, 0xc0000d40c0, 0x119031a, 0x4, 0x0, 0x11c0a40, 0xc0000de100)
  	golang.org/x/tools@v0.0.0-20190625160430-252024b82959/go/ast/astutil/rewrite.go:424 +0x13d7
  golang.org/x/tools/go/ast/astutil.Apply(0x11c0a40, 0xc0000de100, 0xc0000d40a0, 0xc0000d40b0, 0x0, 0x0)
  	golang.org/x/tools@v0.0.0-20190625160430-252024b82959/go/ast/astutil/rewrite.go:52 +0x14a
  mvdan.cc/gofumpt/internal.Gofumpt(0xc0000b2240, 0xc0000de100)
  	mvdan.cc/gofumpt@/internal/gofumpt.go:62 +0x10f
  main.processFile(0x1192301, 0x10, 0x11bfea0, 0xc000078000, 0x11bfec0, 0xc000080000, 0x1, 0x0, 0x0)
  	mvdan.cc/gofumpt@/gofmt.go:121 +0x1ff
  main.gofumptMain()
  	mvdan.cc/gofumpt@/gofmt.go:215 +0x2e6
  main.main()
  	mvdan.cc/gofumpt@/gofmt.go:186 +0x22
  ```
  </details>

Temporary workaround: `gofmt | gofumpt`

>Also panics on `import("a";"b")`, but the behavior is consistent with `gofmt` :bug:.

**Comment by mvdan** [comment]
Thanks for reporting; I can reproduce (if I add a `package p` line first).
